version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Someidiot888@@@
      MYSQL_DATABASE: vacancies_db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"



